---
- name: Create Network
  community.docker.docker_network:
    name: "{{ networkName }}"
    driver: overlay

- name: Deploy services
  include: "../services/{{ item }}/service.yml"
  Vars:
    - name: "{{ item }}"
  loop: "{{ services }}"