---
- name: Join
  community.docker.docker_swarm:
    state: join
    # This addres to connect on swarm
    remote_addrs: "{{ advertise_addr }}"
    join_token: >
      {{
        hostvars['server1']['ansible_facts']['token_worker']
        if type == 'worker' else 
        hostvars['server1']['ansible_facts']['token_manager']
      }}
