---

- name: Swarm join
  vars:
    token: "{{ lookup('file', '../../tokens/token-{{ type }}') }}"
  community.docker.docker_swarm:
    state: join
    # This addres to connect on swarm
    remote_addrs: "{{ advertise_addr }}"
    join_token: "{{ token }}"
