---

- name: "[{{ name }}] Configuration of secret"
  include: "../secret.yml"


- name: "[{{ name }}] Upload service" 
  block:
    - name: "[{{ name }}] Deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: localhost:5000/{{ name }}:latest
        state: present
        networks:
          - name: "{{ networkName }}"
        publish:
          - mode: ingerss
            protocol: tcp
            published_port: 3002 #port in host
            target_port: 3000 #port in container
        secrets: 
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env" # file in container


 

