---

- name: "[{{ name }}] Configuration of secret"
  include_tasks: "../secret.yml"


- name: "[{{ name }}] Upload service" 
  block:
    - name: "[{{ name }}] Deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{registry_name}}{{ name }}:{{ version }}"
        state: present
        # recreate the service. regardless of changes
        force_update: true
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 3002 #port in host
            target_port: 3000 #port in container
        secrets: 
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env" # file in container

  tags: "{{ name }}"


 

