---

- name: "[{{ name }}] Configuration of config"
  include_tasks: "../config.yml"
  loop:
    - nginx.conf
  loop_control:
    loop_var: config_item


- name: "[{{ name }}] Upload service" 
  block:
    - name: "[{{ name }}] Deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "nginx:{{ version }}"
        state: present
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 80 #port in host
            target_port: 80 #port in container
        configs: 
          - config_name: nginx.conf
            filename: "/etc/nginx/nginx.conf" # file in container

  tags: "{{ name }}"


 

