galaxy_info:
  role_name: swarm_leave
  description: Удаление ноды из swarm
  author: Alex
  license: MIT
  min_ansible_version: '2.9'
  platforms: 
  - name: Ubuntu
    versions:
      - all