galaxy_info:
  role_name: preconfig
  description: Настройка серверов для настройки Docker
  author: Alex
  license: MIT
  min_ansible_version: '2.9'
  platforms: 
  - name: Ubuntu
    versions:
      - all
dependencies:
  - role: deploy