---

- name: "[{{ name }}] Upload service" 
  block:
    - name: "[{{ name }}] Deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{registry_name}}{{ name }}:{{ version }}"
        state: present
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 3001 #port in host
            target_port: 80 #port in container
  tags: "{{ name }}"


 

