- name: "[{{ name }}] Create secret" 
  vars: 
    env_file: "{{ lookup('template', '{{ name }}/.env.j2') }}"
  community.docker.docker_secret:
    name: "{{ name }}.env"
    data: "{{ env_file | b64encode }}"
    labels: # We added label, so that we can understand that the secret has changed
      secret: "{{ env_file | hash('sha1') }}"
    data_is_b64: true
    state: present