- name: "[{{ name }}] Create secret" 
  vars: 
    envFile: "{{ lookup('file', '{{ name }}/.env') }}"
  community.docker.docker_secret:
    name: "{{ name }}.env"
    data: "{{ envFile | b64encode }}"
    labels: # We added label, so that we can understand that the secret has changed
      secret: "{{ envFile | hash('sha1') }}"
    data_is_b64: true
    state: present
