- name: "[{{ name }}] Configuration of secret"
  block:
    - name: "[{{ name }}] Create secret" 
      include_tasks: "secret-create.yml"
  tags: "{{ name }}"
  # We grab error.
  rescue: 
  # You killing the service. You trying to change the secret
    - name: "[{{ name }}] Dell service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent
        
    - name: "[{{ name }}] Create secret" 
      include_tasks: "secret-create.yml"