galaxy_info:
  role_name: swarm_init
  description: Инициализация класстера swarm
  author: Alex
  license: MIT
  min_ansible_version: '2.9'
  platforms: 
  - name: Ubuntu
    versions:
      - all